VERSION = "0.10.4"
LICENSE = "MIT - Copyright (c) 2021-2022 Alex Vellone"
MOTORS_CHECK_PER_SECOND = 20
MOTORS_POINT_TO_POINT_CHECK_PER_SECOND = 10
WEB_SOCKET_SEND_PER_SECOND = 10
SOCKET_SEND_PER_SECOND = 20
SOCKET_INCOMING_LIMIT = 5
SLEEP_AVOID_CPU_WASTE = 0.80
