VERSION = "0.5.0"
LICENSE = "MIT - Copyright (c) 2021 Alex Vellone"
MOTORS_CHECK_PER_SECOND = 20
MOTORS_POINT_TO_POINT_CHECK_PER_SECOND = 10
WEB_SOCKET_SEND_PER_SECOND = 10
SOCKET_SEND_PER_SECOND = 20
SOCKET_INCOMING_LIMIT = 5
